### ISSUE TITLE
Sample app needs to have different configs for different environments

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/atsign_pipeline_test#11]
**Describe the solution you'd like**
In at_server we have different URLs for the root server, so to prove out how we create different configs for different environments the sample app needs to read in and display some specific config that's set as an environment secret.

**Additional context**
The work done for at_server secondary:dess_wtf should be relevant here.

Could possibly just be passing an ENV variable into the runtime environment and reading that into the app.

**Comment by sitaram-kalluri** [comment]
The following repository has a sample code to demonstrate different root server URL is picked for different environments. Hence closing the task.
Repository: https://github.com/atsign-foundation/atsign_pipeline_test
